name: End-to-End Testing
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    name: End-to-End Testing
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: End-to-end testing
        run: npm run test